### ISSUE TITLE
Ottimo.

### ISSUE THREAD

**Issue by rd71** [MicrosoftDocs/visualstudio-docs.it-it#13]
Ho trovato queste lezioni molto interessanti e ben fatte, con chiare ed utili spiegazioni.
Grazie molte.
Domenico.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: e918f82f-35af-2934-34d1-913c59cfa927
* Version Independent ID: 009bc101-2451-89b2-5bd1-5ac48a47b33a
* Content: [Informazioni sull'esercitazione Django in Visual Studio, passaggio 6, modello di progetto di sondaggi](https://docs.microsoft.com/it-it/visualstudio/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template?view=vs-2017#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs.it-it/blob/live/docs/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by CeciAc** [comment]
Salve, @rd71 

I tuoi commenti sono molto apprezzati. Siamo lieti di sapere che la documentazione soddisfa le tue aspettative. 
Ci auguriamo che vorrai continuare a inviarci i tuoi utili commenti così che possiamo migliorare ancor di più la tua esperienza. 

Cordiali saluti, 
Il team internazionale Microsoft Docs
