### ISSUE TITLE
Stackless Python

### ISSUE THREAD

**Issue by maxrossi** [MicrosoftDocs/visualstudio-docs.it-it#14]
Stackless Python is supported in mixed-mode debugger?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 702dd6fa-5ad3-b9c7-04bc-e9431c228623
* Version Independent ID: 4d8a2c98-429a-b04e-1489-74475df5951a
* Content: [Debug in modalità mista per Python - Visual Studio](https://docs.microsoft.com/it-it/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.it-it/blob/live/docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @maxrossi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @maxrossi

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
