### ISSUE TITLE
COSE MOLTO INUTILI

### ISSUE THREAD

**Issue by enzonoseda** [MicrosoftDocs/visualstudio-docs.it-it#16]
In tanti anni di programmazione mi sono sempre domandato a cosa servissero questi fasulli esempi di "come realizzare un programma" Inutili perché le applicazioni"consolle" non servono a nulla. Inutili perché così le persone che vorrebbero imparare qualcosa non imparano nulla e anzi vengono allontanate dall'arte di programmare.
Se volete fare FORMAZIONE sulla programmazione create un semplice progetto WINDOWS che gestisce un piccolo database (ad esempio "figure geometriche") che permetta di calcolare e disegnare gli elementi essenziali ad esempio un triangolo, di cui calcolare area, lati, angoli, bisettrice, perimetro ecc. e poi permetta di stampare una pagina e salvarla come PDF oltre a permettere di salvare l'immagine. Insomma un VERO PROGRAMMA completo che consenta di capire tutti gli aspetti della programmazione. 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: dc5022ad-0de6-a16f-3f79-394f57f78903
* Version Independent ID: ecc54693-3334-34f6-ff75-0a0413be4bec
* Content: [Creare per la prima volta un'app console con Visual Basic - Visual Studio](https://docs.microsoft.com/it-it/visualstudio/ide/quickstart-visual-basic-console?view=vs-2019)
* Content Source: [docs/ide/quickstart-visual-basic-console.md](https://github.com/MicrosoftDocs/visualstudio-docs.it-it/blob/live/docs/ide/quickstart-visual-basic-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by srvbpigh** [comment]
Hello, @enzonoseda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Il tuo contributo è molto apprezzato. I tuoi commenti e suggerimenti sono correlati alla documentazione originale.  

Di conseguenza, questa segnalazione verrà inoltrata all'archivio in lingua inglese. Puoi verificare lo stato della segnalazione qui - enzonoseda.  

Il tuo contributo ai nostri articoli è molto apprezzato.   

Cordiali saluti,  
Il team internazionale Microsoft Docs
